server:
  port: 0
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always
    whitelabel:
      enabled: true
    path: /error

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/.report/h2-db
    username: report
    password: report
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

springdoc:
  swagger-ui:
    path: /api-docs.html
    enabled: true
  api-docs:
    enabled: true