server:
  port: 0
  error:
    include-exception: true
    include-message: always
    include-stacktrace: never
    whitelabel:
      enabled: true
    path: /error

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/cafeteria
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    path: /api-docs.html
    enabled: false
  api-docs:
    enabled: false

logging:
  file:
    path: /home/leekyusung/report-service/logs